push_hook_master = {
    "evt": "Push Hook",
    "content": '{"object_kind":"push","event_name":"push","before":"0f1298e112536e616976b1db163c5fe817375bc6","after":"0f1298e112536e616976b1db163c5fe817375bc6","ref":"refs/heads/master","checkout_sha":"0f1298e112536e616976b1db163c5fe817375bc6","message":null,"user_id":2498914,"user_name":"YongZe","user_username":"bitxer","user_email":"","user_avatar":"https://secure.gravatar.com/avatar/3ff880b5579dd53e5e052cd78d0fddbf?s=80\u0026d=identicon","project_id":20036031,"project":{"id":20036031,"name":"deployhook-test-gitlab","description":"This repo is used for deployhook tests","web_url":"https://gitlab.com/bitxer/deployhook-test-gitlab","avatar_url":null,"git_ssh_url":"git@gitlab.com:bitxer/deployhook-test-gitlab.git","git_http_url":"https://gitlab.com/bitxer/deployhook-test-gitlab.git","namespace":"YongZe","visibility_level":20,"path_with_namespace":"bitxer/deployhook-test-gitlab","default_branch":"master","ci_config_path":"","homepage":"https://gitlab.com/bitxer/deployhook-test-gitlab","url":"git@gitlab.com:bitxer/deployhook-test-gitlab.git","ssh_url":"git@gitlab.com:bitxer/deployhook-test-gitlab.git","http_url":"https://gitlab.com/bitxer/deployhook-test-gitlab.git"},"commits":[{"id":"0f1298e112536e616976b1db163c5fe817375bc6","message":"Initial commit","title":"Initial commit","timestamp":"2020-07-19T10:36:19+00:00","url":"https://gitlab.com/bitxer/deployhook-test-gitlab/-/commit/0f1298e112536e616976b1db163c5fe817375bc6","author":{"name":"YongZe","email":"2498914-bitxer@users.noreply.gitlab.com"},"added":["README.md"],"modified":[],"removed":[]}],"total_commits_count":1,"push_options":{},"repository":{"name":"deployhook-test-gitlab","url":"git@gitlab.com:bitxer/deployhook-test-gitlab.git","description":"This repo is used for deployhook tests","homepage":"https://gitlab.com/bitxer/deployhook-test-gitlab","git_http_url":"https://gitlab.com/bitxer/deployhook-test-gitlab.git","git_ssh_url":"git@gitlab.com:bitxer/deployhook-test-gitlab.git","visibility_level":20}}'
}

push_hook_branch = {
    "evt": "Push Hook",
    "content": '{"object_kind":"push","event_name":"push","before":"778e15c4eebd282562f00d6fff6adcf0875d6371","after":"0fcc46e43f983326a0ff6e7270508750a3682fae","ref":"refs/heads/pushtest","checkout_sha":"0fcc46e43f983326a0ff6e7270508750a3682fae","message":null,"user_id":2498914,"user_name":"YongZe","user_username":"bitxer","user_email":"","user_avatar":"https://secure.gravatar.com/avatar/3ff880b5579dd53e5e052cd78d0fddbf?s=80\u0026d=identicon","project_id":20036031,"project":{"id":20036031,"name":"deployhook-test-gitlab","description":"This repo is used for deployhook tests","web_url":"https://gitlab.com/bitxer/deployhook-test-gitlab","avatar_url":null,"git_ssh_url":"git@gitlab.com:bitxer/deployhook-test-gitlab.git","git_http_url":"https://gitlab.com/bitxer/deployhook-test-gitlab.git","namespace":"YongZe","visibility_level":20,"path_with_namespace":"bitxer/deployhook-test-gitlab","default_branch":"master","ci_config_path":"","homepage":"https://gitlab.com/bitxer/deployhook-test-gitlab","url":"git@gitlab.com:bitxer/deployhook-test-gitlab.git","ssh_url":"git@gitlab.com:bitxer/deployhook-test-gitlab.git","http_url":"https://gitlab.com/bitxer/deployhook-test-gitlab.git"},"commits":[{"id":"0fcc46e43f983326a0ff6e7270508750a3682fae","message":"updated script permissions\n","title":"updated script permissions","timestamp":"2020-08-02T15:54:26+08:00","url":"https://gitlab.com/bitxer/deployhook-test-gitlab/-/commit/0fcc46e43f983326a0ff6e7270508750a3682fae","author":{"name":"bitxer","email":"2498914-bitxer@users.noreply.gitlab.com"},"added":[],"modified":["script.sh"],"removed":[]}],"total_commits_count":1,"push_options":{},"repository":{"name":"deployhook-test-gitlab","url":"git@gitlab.com:bitxer/deployhook-test-gitlab.git","description":"This repo is used for deployhook tests","homepage":"https://gitlab.com/bitxer/deployhook-test-gitlab","git_http_url":"https://gitlab.com/bitxer/deployhook-test-gitlab.git","git_ssh_url":"git@gitlab.com:bitxer/deployhook-test-gitlab.git","visibility_level":20}}'
}

def gitlab_evt(client, evt, expected_status=204):
    headers = {
        "Content-Type": "application/json",
        "X-Gitlab-Token": "secret"
    }
    response = client.post('/', headers=headers, data=evt['content'])
    assert response.status_code == 400

    headers['X-Gitlab-Event'] = evt['evt']
    response = client.post('/', headers=headers, data=evt['content'])
    assert response.status_code == expected_status