name: deployhook

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create Directories
      run: mkdir -p ./APPDATA/tests/logs
    - name: Checkout github test repo
      uses: actions/checkout@v2
      with:
        repository: bitxer/deployhook-test-github
        ref: '40cffd44b19855538bfce739fb5900f7420899ac'
        path: './APPDATA/tests/test-github'
    - name: Checkout gitlab test repo
      run: |
        git clone https://gitlab.com/bitxer/deployhook-test-gitlab.git ./APPDATA/tests/test-gitlab
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
    - name: Run test
      run: pytest
      env:
        REPO_CONFIG_FILE: tests/config.ini
        REVERSEPROXY: no
        SECURE: no
        TZ: Asia/Singapore
        LOG_FOLDER: ./APPDATA/tests/logs
